// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(2545074965);
}

export function Echo(message: string): $CancellablePromise<string> {
    return $Call.ByID(3620578863, message);
}

export function SetAutoCheckUpdates(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2957917899, enabled);
}

export function SetAutoDownloadUpdates(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3871382773, enabled);
}

export function SetAutoStart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(351485835, enabled);
}

/**
 * SetAutoStartShowWindow updates both the saved preference and an existing registration.
 */
export function SetAutoStartShowWindow(show: boolean): $CancellablePromise<void> {
    return $Call.ByID(1039525058, show);
}

export function SetCloseToTray(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(321281083, enabled);
}

export function State(): $CancellablePromise<$models.DesktopState> {
    return $Call.ByID(929829011);
}
