// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DesktopService from "./desktopservice.js";
import * as LocalServer from "./localserver.js";
export {
    DesktopService,
    LocalServer
};

export type {
    DesktopState,
    LocalServerStatus
} from "./models.js";
