// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DesktopState {
    "name": string;
    "version": string;
    "commit": string;
    "buildTime": string;
    "platform": string;
    "architecture": string;
    "autoStart": boolean;
    "autoStartShowWindow": boolean;
    "autoStartWindowSupported": boolean;
    "configPath": string;
    "configError"?: string;
    "autoStartError"?: string;
    "closeToTray": boolean;
    "trayReady": boolean;
    "updateRepository": string;
    "updateInstallHint"?: string;
    "updateIntervalHours": number;
    "localServer": LocalServerStatus;
    "websocketURL": string;
}

export interface LocalServerStatus {
    "address": string;
    "running": boolean;
}
