// Buildmeta synchronises platform packaging metadata from project/app.json.
package main

import (
	"bytes"
	"changeme/project"
	"encoding/json"
	"encoding/xml"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strings"
	"time"
)

func main() {
	release := flag.Bool("release", false, "require VERSION from a release tag")
	flag.Parse()
	if err := generate(project.Load(), *release); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func writeChanged(path string, data []byte) error {
	old, _ := os.ReadFile(path)
	if bytes.Equal(old, data) {
		return nil
	}
	return os.WriteFile(path, data, 0644)
}

func replace(path, pattern, replacement string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	// Git may check out text files with CRLF on Windows. Match against LF,
	// then restore the input's newline style to avoid mixed line endings.
	crlf := bytes.Contains(data, []byte("\r\n"))
	data = bytes.ReplaceAll(data, []byte("\r\n"), []byte("\n"))
	re := regexp.MustCompile(pattern)
	if !re.Match(data) {
		return fmt.Errorf("metadata field missing in %s: %s", path, pattern)
	}
	updated := re.ReplaceAllFunc(data, func([]byte) []byte { return []byte(replacement) })
	if crlf {
		updated = bytes.ReplaceAll(updated, []byte("\n"), []byte("\r\n"))
	}
	return writeChanged(path, updated)
}

func xmlText(value string) string {
	var b bytes.Buffer
	_ = xml.EscapeText(&b, []byte(value))
	return b.String()
}

func generate(c project.Config, release bool) error {
	version := strings.TrimPrefix(strings.TrimSpace(os.Getenv("VERSION")), "v")
	if version == "" {
		if release {
			return fmt.Errorf("VERSION is required for release builds")
		}
		version = c.DevVersion
	}
	numeric, err := project.NumericVersion(version)
	if err != nil {
		return err
	}
	commit, buildTime := "dev", "unknown"
	if os.Getenv("VERSION") != "" {
		commit = strings.TrimSpace(os.Getenv("COMMIT"))
		if commit == "" {
			commit = "unknown"
		}
		buildTime = time.Now().UTC().Format(time.RFC3339)
	}

	content, err := format.Source([]byte(fmt.Sprintf("// Code generated by cmd/buildmeta; DO NOT EDIT.\npackage server\nvar (Version = %q; Commit = %q; BuildTime = %q)\n", version, commit, buildTime)))
	if err != nil {
		return err
	}
	if err = writeChanged("server/version_generated.go", content); err != nil {
		return err
	}

	info := fmt.Sprintf("info:\n  companyName: %q\n  productName: %q\n  productIdentifier: %q\n  description: %q\n  copyright: %q\n  comments: %q\n  version: %q\n", c.CompanyName, c.Name, c.Identifier, c.Description, c.Copyright, c.Description, numeric)
	if err = replace("build/config.yml", `(?ms)^info:\n.*?\n\n`, info+"\n"); err != nil {
		return err
	}

	win := map[string]any{"fixed": map[string]string{"file_version": numeric}, "info": map[string]any{"0000": map[string]string{"ProductVersion": version, "CompanyName": c.CompanyName, "FileDescription": c.Description, "LegalCopyright": c.Copyright, "ProductName": c.Name, "Comments": c.Description}}}
	data, _ := json.MarshalIndent(win, "", "  ")
	if err = writeChanged("build/windows/info.json", append(data, '\n')); err != nil {
		return err
	}

	nsis := fmt.Sprintf("; Code generated by cmd/buildmeta; DO NOT EDIT.\n!define INFO_PROJECTNAME %q\n!define INFO_COMPANYNAME %q\n!define INFO_PRODUCTNAME %q\n!define INFO_PRODUCTVERSION %q\n!define INFO_COPYRIGHT %q\n!define APP_IDENTIFIER %q\n!define UNINST_KEY_NAME %q\n", c.BinaryName, c.CompanyName, c.Name, numeric, c.Copyright, c.Identifier, c.Identifier)
	if err = writeChanged("build/windows/nsis/app_generated.nsh", []byte(nsis)); err != nil {
		return err
	}

	for _, path := range []string{"build/darwin/Info.plist", "build/darwin/Info.dev.plist"} {
		if _, err := os.Stat(path); os.IsNotExist(err) {
			continue
		}
		for key, value := range map[string]string{"CFBundleName": c.Name, "CFBundleExecutable": c.BinaryName, "CFBundleIdentifier": c.Identifier, "CFBundleVersion": numeric, "CFBundleShortVersionString": numeric, "CFBundleGetInfoString": c.Description, "NSHumanReadableCopyright": c.Copyright} {
			if err = replace(path, `<key>`+key+`</key>\s*<string>[^<]*</string>`, "<key>"+key+"</key>\n            <string>"+xmlText(value)+"</string>"); err != nil {
				return err
			}
		}
	}

	// Keep a stable source path for Linux desktop metadata. The installed file
	// name still uses BinaryName, but changing BinaryName never leaves stale
	// build/linux/<old-name>.desktop files behind in the template repository.
	desktop := fmt.Sprintf("# Code generated by cmd/buildmeta; DO NOT EDIT.\n[Desktop Entry]\nType=Application\nName=%s\nComment=%s\nExec=%s\nIcon=%s\nCategories=Utility;\nTerminal=false\nStartupNotify=false\n", c.Name, c.Description, c.BinaryName, c.BinaryName)
	if err = writeChanged("build/linux/desktop", []byte(desktop)); err != nil {
		return err
	}

	for key, value := range map[string]string{"name": c.BinaryName, "version": version, "description": c.Description, "vendor": c.CompanyName, "maintainer": c.CompanyName, "homepage": "https://github.com/" + c.UpdateRepository} {
		if err = replace("build/linux/nfpm/nfpm.yaml", `(?m)^`+key+`: "[^"]*"`, fmt.Sprintf("%s: %q", key, value)); err != nil {
			return err
		}
	}
	contents := fmt.Sprintf("contents:\n  - src: %q\n    dst: %q\n    file_info:\n      mode: 0755\n  - src: \"./build/appicon.png\"\n    dst: %q\n    file_info:\n      mode: 0644\n  - src: %q\n    dst: %q\n    file_info:\n      mode: 0644\n", "./bin/"+c.BinaryName, "/usr/bin/"+c.BinaryName, "/usr/share/icons/hicolor/128x128/apps/"+c.BinaryName+".png", "./build/linux/desktop", "/usr/share/applications/"+c.BinaryName+".desktop")
	if err = replace("build/linux/nfpm/nfpm.yaml", `(?ms)^contents:\n.*?\n\n`, contents+"\n"); err != nil {
		return err
	}

	if err = replace("frontend/index.html", `<title>[^<]*</title>`, "<title>"+xmlText(c.Name)+"</title>"); err != nil {
		return err
	}

	// GitHub Actions consumes the same validated binary name as Taskfile and
	// packaging metadata. Version intentionally stays in the release/tag only.
	if path := os.Getenv("GITHUB_ENV"); path != "" {
		f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0600)
		if err != nil {
			return err
		}
		_, err = fmt.Fprintf(f, "APP_NAME=%s\nASSET_PREFIX=%s\n", c.BinaryName, c.BinaryName)
		closeErr := f.Close()
		if err != nil {
			return err
		}
		return closeErr
	}
	return nil
}
