// Buildmeta synchronises platform packaging metadata from project/app.json.
package main

import (
	"bytes"
	"changeme/project"
	"encoding/json"
	"encoding/xml"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

const generatedMarker = "Code generated by cmd/buildmeta; DO NOT EDIT."

func main() {
	release := flag.Bool("release", false, "require VERSION from a release tag")
	flag.Parse()
	if err := generate(project.Load(), *release); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func writeChanged(path string, data []byte) error {
	old, _ := os.ReadFile(path)
	if bytes.Equal(old, data) {
		return nil
	}
	return os.WriteFile(path, data, 0644)
}

func replace(path, pattern, replacement string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	// Git may check out text files with CRLF on Windows. Match against LF,
	// then restore the input's newline style to avoid mixed line endings.
	crlf := bytes.Contains(data, []byte("\r\n"))
	data = bytes.ReplaceAll(data, []byte("\r\n"), []byte("\n"))
	re := regexp.MustCompile(pattern)
	if !re.Match(data) {
		return fmt.Errorf("metadata field missing in %s: %s", path, pattern)
	}
	updated := re.ReplaceAllFunc(data, func([]byte) []byte { return []byte(replacement) })
	if crlf {
		updated = bytes.ReplaceAll(updated, []byte("\n"), []byte("\r\n"))
	}
	return writeChanged(path, updated)
}

func xmlText(value string) string {
	var b bytes.Buffer
	_ = xml.EscapeText(&b, []byte(value))
	return b.String()
}

// xmlAttribute edits only the selected element, preserving namespaces and layout.
func xmlAttribute(path, tag, key, value string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	re := regexp.MustCompile(`<` + regexp.QuoteMeta(tag) + `\b[^>]*>`)
	attr := regexp.MustCompile(`\b` + regexp.QuoteMeta(key) + `="[^"]*"`)
	found := false
	data = re.ReplaceAllFunc(data, func(element []byte) []byte {
		if !attr.Match(element) {
			return element
		}
		found = true
		return attr.ReplaceAllFunc(element, func([]byte) []byte { return []byte(key + `="` + xmlText(value) + `"`) })
	})
	if !found {
		return fmt.Errorf("metadata attribute missing in %s: %s.%s", path, tag, key)
	}
	return writeChanged(path, data)
}

func platformMetadata(c project.Config, numeric string) error {
	// Select the application's identity, never the Common Controls dependency.
	if err := replace("build/windows/wails.exe.manifest", `(<assemblyIdentity type="win32" name=")[^"]*(" version=")[^"]*(" processorArchitecture="\*"/>)`,
		`<assemblyIdentity type="win32" name="`+xmlText(c.Identifier)+`" version="`+numeric+`.0" processorArchitecture="*"/>`); err != nil {
		return err
	}
	for key, value := range map[string]string{"INFO_PROJECTNAME": c.BinaryName, "INFO_COMPANYNAME": c.CompanyName, "INFO_PRODUCTNAME": c.Name, "INFO_PRODUCTVERSION": numeric, "INFO_COPYRIGHT": c.Copyright} {
		if err := replace("build/windows/nsis/wails_tools.nsh", `(?m)!define `+key+` "[^"]*"`, fmt.Sprintf("!define %s %q", key, value)); err != nil {
			return err
		}
	}
	for _, path := range []string{"build/windows/msix/app_manifest.xml", "build/windows/msix/template.xml"} {
		for key, value := range map[string]string{"DisplayName": c.Name, "PublisherDisplayName": c.CompanyName, "Description": c.Description} {
			if err := replace(path, `<`+key+`>[^<]*</`+key+`>`, `<`+key+`>`+xmlText(value)+`</`+key+`>`); err != nil {
				return err
			}
		}
	}
	for _, item := range []struct{ path, tag, key, value string }{
		{"build/windows/msix/app_manifest.xml", "Identity", "Name", c.Identifier},
		{"build/windows/msix/app_manifest.xml", "Identity", "Publisher", "CN=" + c.CompanyName},
		{"build/windows/msix/app_manifest.xml", "Identity", "Version", numeric + ".0"},
		{"build/windows/msix/app_manifest.xml", "Application", "Id", "App"},
		{"build/windows/msix/app_manifest.xml", "Application", "Executable", c.BinaryName + ".exe"},
		{"build/windows/msix/app_manifest.xml", "desktop:Extension", "Executable", c.BinaryName + ".exe"},
		{"build/windows/msix/app_manifest.xml", "uap:VisualElements", "DisplayName", c.Name},
		{"build/windows/msix/app_manifest.xml", "uap:VisualElements", "Description", c.Description},
		{"build/windows/msix/template.xml", "Installer", "Path", c.BinaryName + "-amd64-installer.exe"},
		{"build/windows/msix/template.xml", "Installer", "InstallLocation", `C:\Program Files\` + c.CompanyName + `\` + c.Name},
		{"build/windows/msix/template.xml", "PackageInformation", "PackageName", c.Identifier},
		{"build/windows/msix/template.xml", "PackageInformation", "PackageDisplayName", c.Name},
		{"build/windows/msix/template.xml", "PackageInformation", "PublisherName", "CN=" + c.CompanyName},
		{"build/windows/msix/template.xml", "PackageInformation", "PublisherDisplayName", c.CompanyName},
		{"build/windows/msix/template.xml", "PackageInformation", "Version", numeric + ".0"},
		{"build/windows/msix/template.xml", "PackageInformation", "PackageDescription", c.Description},
		{"build/windows/msix/template.xml", "Application", "Id", "App"},
		{"build/windows/msix/template.xml", "Application", "Description", c.Description},
		{"build/windows/msix/template.xml", "Application", "DisplayName", c.Name},
		{"build/windows/msix/template.xml", "Application", "ExecutableName", c.BinaryName + ".exe"},
		{"build/windows/msix/template.xml", "SaveLocation", "PackagePath", c.BinaryName + ".msix"},
	} {
		if err := xmlAttribute(item.path, item.tag, item.key, item.value); err != nil {
			return err
		}
	}
	for _, path := range []string{"build/ios/Info.plist", "build/ios/Info.dev.plist"} {
		name, identifier := c.Name, c.Identifier
		if strings.Contains(path, ".dev.") {
			name += " (Dev)"
			identifier += ".dev"
		}
		for key, value := range map[string]string{"CFBundleName": name, "CFBundleDisplayName": name, "CFBundleExecutable": c.BinaryName, "CFBundleIdentifier": identifier, "CFBundleVersion": numeric, "CFBundleShortVersionString": numeric, "CFBundleGetInfoString": c.Description, "NSHumanReadableCopyright": c.Copyright} {
			if err := replace(path, `<key>`+key+`</key>\s*<string>[^<]*</string>`, "<key>"+key+"</key>\n    <string>"+xmlText(value)+"</string>"); err != nil {
				return err
			}
		}
	}
	path := "build/ios/project.pbxproj"
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	match := regexp.MustCompile(`PRODUCT_NAME = "([^"]+)";`).FindSubmatch(data)
	if match == nil {
		return fmt.Errorf("PRODUCT_NAME missing in %s", path)
	}
	if err := replace(path, regexp.QuoteMeta(string(match[1])), c.BinaryName); err != nil {
		return err
	}
	for key, value := range map[string]string{"PRODUCT_BUNDLE_IDENTIFIER": c.Identifier, "ORGANIZATIONNAME": c.CompanyName} {
		if err := replace(path, key+` = "[^"]*";`, fmt.Sprintf("%s = %q;", key, value)); err != nil {
			return err
		}
	}
	for id, value := range map[string]string{"GJd-Yh-RWb": c.Name, "MN2-I3-ftu": c.Description} {
		path := "build/ios/LaunchScreen.storyboard"
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		re := regexp.MustCompile(`<label\b[^>]*id="` + id + `"[^>]*>`)
		element := re.Find(data)
		if element == nil {
			return fmt.Errorf("launch label missing: %s", id)
		}
		updated := regexp.MustCompile(`text="[^"]*"`).ReplaceAllString(string(element), "text=\""+xmlText(value)+"\"")
		if err := replace(path, regexp.QuoteMeta(string(element)), updated); err != nil {
			return err
		}
	}
	// Java/JNI classes retain their framework namespace; only app identity changes.
	androidID := strings.ReplaceAll(c.Identifier, "-", "_")
	for _, item := range []struct{ path, pattern, value string }{
		{"build/android/app/build.gradle", `applicationId "[^"]*"`, `applicationId "` + androidID + `"`},
		{"build/android/app/build.gradle", `versionName "[^"]*"`, `versionName "` + numeric + `"`},
		{"build/android/settings.gradle", `rootProject.name = "[^"]*"`, `rootProject.name = "` + c.BinaryName + `"`},
		{"build/android/app/src/main/res/values/strings.xml", `<string name="app_name">[^<]*</string>`, `<string name="app_name">"` + xmlText(c.Name) + `"</string>`},
	} {
		if err := replace(item.path, item.pattern, item.value); err != nil {
			return err
		}
	}
	return nil
}

func cleanupGeneratedDesktopFiles(current string) error {
	paths, err := filepath.Glob("build/linux/*.desktop")
	if err != nil {
		return err
	}
	for _, path := range paths {
		if filepath.Clean(path) == filepath.Clean(current) {
			continue
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !bytes.Contains(data, []byte(generatedMarker)) {
			continue
		}
		if err := os.Remove(path); err != nil {
			return err
		}
	}
	return nil
}

func generate(c project.Config, release bool) error {
	version := strings.TrimPrefix(strings.TrimSpace(os.Getenv("VERSION")), "v")
	if version == "" {
		if release {
			return fmt.Errorf("VERSION is required for release builds")
		}
		version = c.DevVersion
	}
	numeric, err := project.NumericVersion(version)
	if err != nil {
		return err
	}
	commit, buildTime := "dev", "unknown"
	if os.Getenv("VERSION") != "" {
		commit = strings.TrimSpace(os.Getenv("COMMIT"))
		if commit == "" {
			commit = "unknown"
		}
		buildTime = time.Now().UTC().Format(time.RFC3339)
	}

	content, err := format.Source([]byte(fmt.Sprintf("// %s\npackage desktop\nvar (Version = %q; Commit = %q; BuildTime = %q)\n", generatedMarker, version, commit, buildTime)))
	if err != nil {
		return err
	}
	if err = writeChanged("server/desktop/version_generated.go", content); err != nil {
		return err
	}

	info := fmt.Sprintf("info:\n  companyName: %q\n  productName: %q\n  productIdentifier: %q\n  description: %q\n  copyright: %q\n  comments: %q\n  version: %q\n", c.CompanyName, c.Name, c.Identifier, c.Description, c.Copyright, c.Description, numeric)
	if err = replace("build/config.yml", `(?ms)^info:\n.*?\n\n`, info+"\n"); err != nil {
		return err
	}

	win := map[string]any{"fixed": map[string]string{"file_version": numeric}, "info": map[string]any{"0000": map[string]string{"ProductVersion": version, "CompanyName": c.CompanyName, "FileDescription": c.Description, "LegalCopyright": c.Copyright, "ProductName": c.Name, "Comments": c.Description}}}
	data, _ := json.MarshalIndent(win, "", "  ")
	if err = writeChanged("build/windows/info.json", append(data, '\n')); err != nil {
		return err
	}

	nsis := fmt.Sprintf("; %s\n!define INFO_PROJECTNAME %q\n!define INFO_COMPANYNAME %q\n!define INFO_PRODUCTNAME %q\n!define INFO_PRODUCTVERSION %q\n!define INFO_COPYRIGHT %q\n!define APP_IDENTIFIER %q\n!define UNINST_KEY_NAME %q\n", generatedMarker, c.BinaryName, c.CompanyName, c.Name, numeric, c.Copyright, c.Identifier, c.Identifier)
	if err = writeChanged("build/windows/nsis/app_generated.nsh", []byte(nsis)); err != nil {
		return err
	}

	for _, path := range []string{"build/darwin/Info.plist", "build/darwin/Info.dev.plist"} {
		if _, err := os.Stat(path); os.IsNotExist(err) {
			continue
		}
		for key, value := range map[string]string{"CFBundleName": c.Name, "CFBundleExecutable": c.BinaryName, "CFBundleIdentifier": c.Identifier, "CFBundleVersion": numeric, "CFBundleShortVersionString": numeric, "CFBundleGetInfoString": c.Description, "NSHumanReadableCopyright": c.Copyright} {
			if err = replace(path, `<key>`+key+`</key>\s*<string>[^<]*</string>`, "<key>"+key+"</key>\n            <string>"+xmlText(value)+"</string>"); err != nil {
				return err
			}
		}
	}

	if err := platformMetadata(c, numeric); err != nil {
		return err
	}

	// Linux uses a binary-named desktop file for AppImage plus a stable source
	// for system packages. Generated binary-named files are cleaned on rename.
	desktop := fmt.Sprintf("# %s\n[Desktop Entry]\nType=Application\nName=%s\nComment=%s\nExec=%s\nIcon=%s\nCategories=Utility;\nTerminal=false\nStartupNotify=false\n", generatedMarker, c.Name, c.Description, c.BinaryName, c.BinaryName)
	currentDesktop := filepath.Join("build", "linux", c.BinaryName+".desktop")
	if err = cleanupGeneratedDesktopFiles(currentDesktop); err != nil {
		return err
	}
	if err = writeChanged(currentDesktop, []byte(desktop)); err != nil {
		return err
	}
	if err = writeChanged("build/linux/desktop", []byte(desktop)); err != nil {
		return err
	}

	for key, value := range map[string]string{"name": c.BinaryName, "version": version, "description": c.Description, "vendor": c.CompanyName, "maintainer": c.CompanyName, "homepage": c.UpdateRepositoryURL} {
		if err = replace("build/linux/nfpm/nfpm.yaml", `(?m)^`+key+`: "[^"]*"`, fmt.Sprintf("%s: %q", key, value)); err != nil {
			return err
		}
	}
	contents := fmt.Sprintf("contents:\n  - src: %q\n    dst: %q\n    file_info:\n      mode: 0755\n  - src: \"./build/appicon.png\"\n    dst: %q\n    file_info:\n      mode: 0644\n  - src: %q\n    dst: %q\n    file_info:\n      mode: 0644\n", "./bin/"+c.BinaryName, "/usr/bin/"+c.BinaryName, "/usr/share/icons/hicolor/128x128/apps/"+c.BinaryName+".png", "./build/linux/desktop", "/usr/share/applications/"+c.BinaryName+".desktop")
	if err = replace("build/linux/nfpm/nfpm.yaml", `(?ms)^contents:\n.*?\n\n`, contents+"\n"); err != nil {
		return err
	}

	if err = replace("frontend/index.html", `<title>[^<]*</title>`, "<title>"+xmlText(c.Name)+"</title>"); err != nil {
		return err
	}

	// CI consumes the same validated binary name as Taskfile and packaging
	// metadata. Version intentionally stays in the release/tag only.
	if path := os.Getenv("GITHUB_ENV"); path != "" {
		f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0600)
		if err != nil {
			return err
		}
		_, err = fmt.Fprintf(f, "APP_NAME=%s\nASSET_PREFIX=%s\n", c.BinaryName, c.BinaryName)
		closeErr := f.Close()
		if err != nil {
			return err
		}
		return closeErr
	}
	return nil
}
