// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(1628387972);
}

export function Echo(message: string): $CancellablePromise<string> {
    return $Call.ByID(1900927664, message);
}

export function SetAutoCheckUpdates(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2647775754, enabled);
}

export function SetAutoDownloadUpdates(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3805191626, enabled);
}

export function SetAutoStart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1410730328, enabled);
}

/**
 * SetAutoStartShowWindow updates both the saved preference and an existing registration.
 */
export function SetAutoStartShowWindow(show: boolean): $CancellablePromise<void> {
    return $Call.ByID(1442451505, show);
}

export function SetCloseToTray(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2040074940, enabled);
}

export function State(): $CancellablePromise<$models.DesktopState> {
    return $Call.ByID(2060267618);
}
