// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DesktopService from "./desktopservice.js";
export {
    DesktopService
};

export type {
    DesktopState
} from "./models.js";
