// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as localapi$0 from "../localapi/models.js";

export interface DesktopState {
    "name": string;
    "version": string;
    "commit": string;
    "buildTime": string;
    "platform": string;
    "architecture": string;
    "autoStart": boolean;
    "autoStartShowWindow": boolean;
    "autoStartWindowSupported": boolean;
    "configPath": string;
    "configError"?: string;
    "autoStartError"?: string;
    "closeToTray": boolean;
    "trayReady": boolean;
    "autoCheckUpdates": boolean;
    "autoDownloadUpdates": boolean;
    "updateRepositoryURL": string;
    "updateInstallHint"?: string;
    "updateIntervalHours": number;
    "localServer": localapi$0.Status;
    "websocketURL": string;
}
